import { CompanyFormValues } from '../types/formTypes'

export const initialValues: CompanyFormValues = {
  companyName: { en: '', fr: '' },
  corporationNumber: '',
  federalBusinessRegistryNumber: 0,
  incorporationDate: null,
  organizationType: '',
  sector: [],
  companyLogo: '',
  customerSatisfactionScore: null,
  environmentalImpact: '',
  grantMatchScore: null,
  innovationScore: null,
  queryPerformanceScore: null,
  totalEmployeeCount: null,
  aiAnalysis: {
    aiAnalysisDate: null,
    aiAnalysisReady: false,
    aiImprovementRecommendations: '',
    aiReadinessDetails: '',
  },
  clientId: '',
  address: {
    city: '',
    country: '',
    line1: '',
    line2: '',
    state: '',
    zipCode: '',
  },
  socialMediaLinks: [],
  type: '',
  website: '',
  currentDebtAmount: 0,
  debtType: '',
  notes: '',
  paymentSchedule: '',
  supportingDocuments: {},
  title: '',
  documentType: '',
  tags: [],
  fileId: '',
  documentVersions: [],
  annualFinancials: [],
  financialStatements: [],
  amountReceived: 0,
  date: null,
  investorInfo: {
    name: '',
    contact: '',
    details: '',
  },
  ipId: '',
  ipType: '',
  ipTitle: '',
  ipDescription: '',
  ipNotes: '',
  ipSupportingDocuments: {},
  management: {},
  ownership: {},
  employeeCount: [],
  futureRevenueProjections: [],
  growthPlans: {
    growthPlans: '',
    supportingDocumentation: {},
  },
  detailedDescription: '',
  technologySupportingDocuments: {},
  primaryContacts: [],
  secondaryContact: {
    name: '',
    role: '',
    contactInfo: {
      email: '',
      phone: '',
    },
    linkedInProfile: '',
    resumeMetadata: '',
    notes: '',
  },
  amountRequested: 0,
  dueDate: null,
  endDate: null,
  financialTracking: {
    categorySubtotals: {},
    fundspokeEmployee: '',
    fundspokeWriterTeam: '',
  },
  programName: '',
  projectSummary: '',
  projectTimeline: {
    startDate: null,
    endDate: null,
    note: '',
  },
  projectTitle: '',
  reporting: [],
  status: '',
  submissionDate: null,
  claims: [],
  fundingSupportingDocuments: [],
  keyword: '',
  memberId: '',
  memberName: '',
  memberRole: '',
  memberContactInfo: {
    email: '',
    phone: '',
  },
  memberLinkedInProfile: '',
  memberResumeMetadata: '',
  memberNotes: '',
  batchId: '',
  changeImpact: '',
  changeReason: '',
  entity: '',
  field: '',
  modifiedBy: '',
  newValue: '',
  previousValue: '',
}